keys:
  - &astukalov-thinkpad age1fc7enet4cm9alx5tdxr3ec90fpt3layxvrct4kt0jluzgm8mh9fqdxc5ls
  - &msi-laptop age111111

creation_rules:
  - path_regex: secrets/astukalov-thinkpad/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *astukalov-thinkpad

  - path_regex: secrets/msi-laptop/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *msi-laptop
