keys:
  - &astukalov-thinkpad age1fc7enet4cm9alx5tdxr3ec90fpt3layxvrct4kt0jluzgm8mh9fqdxc5ls

creation_rules:
  # Секреты для astukalov-thinkpad
  - path_regex: secrets/astukalov-thinkpad/[^/]+$
    key_groups:
      - age:
          - *astukalov-thinkpad
