keys:
  - &msi-laptop age1xnpmkazfqytegvunnuzyds6llz2x8hjuj08u5t506hhgu2tj09vss7lj98
  - &sdev-pc age143vsyd3eqfhdfjh7uhdgx6wnk42r0msgp7s8uquajq32culttevs2ce82n

creation_rules:
  - path_regex: secrets/msi-laptop.yaml
    key_groups:
      - age:
          - *msi-laptop
  - path_regex: secrets/sdev-pc.yaml
    key_groups:
      - age:
          - *sdev-pc
